### ISSUE TITLE
RTD broken

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-docs#21]
https://readthedocs.org/projects/open-forcefield-toolkit/builds/21497969/

```
/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/dist.py:510: SetuptoolsDeprecationWarning: Invalid version: 'stable+10.gf5ec529.dirty'.
!!

        ********************************************************************************
        The version specified is not a valid version according to PEP 440.
        This may not work as expected with newer versions of
        setuptools, pip, and PyPI.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  self._validate_version(self.metadata.version)
running install
/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'stable+10.gf5ec529.dirty'.
!!

        ********************************************************************************
        Version 'stable+10.gf5ec529.dirty' is not valid according to PEP 440.

        Please make sure to specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  return _normalization.best_effort_version(tagged)
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/checkouts/1679/./setup.py", line 17, in <module>
    setup(
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 92, in finalize_options
    ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 218, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/1679/lib/python3.9/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'stable-10.gf5ec529.dirty'
Command time: 0s Return: 1

**Comment by j-wags** [comment]
Let's give this one a day to shake out - I did the last OFFTK release a little bit out of order (merged the postrelease PR BEFORE I updated the stable tag) so it may just be that I need to manually change the stable tag back a bit.

**Comment by mattwthompson** [comment]
There could be something wrong with how RTD is running things, but I suspect it's actually SetupTools providing a wrong version string to something. I'm going to work on this locally to try to isolate the cause.

**Comment by mattwthompson** [comment]
https://github.com/openforcefield/openff-toolkit/pull/1687 might fix this; it at least fixes PR builds

**Comment by j-wags** [comment]
This appears to have been fixed by me making a release of OFFTK without mangling the step where I update the stable tag 🤦
